#!/bin/sh

# passmenu fill-in

password="$(find \
	"${PASSWORD_STORE_DIR:-$HOME/.password-store}"/* \
	-type f \
	-exec sh -c \
	'i="${1##*/}"; i="${i%.gpg}"; printf "%s\n" "$i"' \
	_ {} \; | dmenu)"

[ -z "$password" ] && exit

IFS= read -r gpgid <"${PASSWORD_STORE_DIR:-$HOME/.password-store}/.gpg-id"

[ -n "$TMUX" ] \
	&& { { echo "dummy" | env GPG_TTY="$TTY" gpg \
	--no-verbose --quiet --batch \
	--local-user "$gpgid" \
	--pinentry-mode error \
	--sign >/dev/null 2>&1 ;} \
	|| { tmux display-popup \
	-w 58 -h 14 -E \
	-e gpgid="$gpgid" \
	'echo "dummy" \
	| env GPG_TTY="$TTY" gpg \
	--no-verbose --quiet --batch \
	--local-user "$gpgid" \
	--sign >/dev/null 2>&1' ;} }

[ "$1" = "--type" ] \
	&& { pass show "$password" \
		| { IFS= read -r pass; printf %s "$pass" ;} \
		| xdotool type --clearmodifiers --file - ;} \
	|| pass show -c "$password" 2>/dev/null
