#!/bin/sh

# st wrapper for tmux

for o in "$@"; do case "$o" in
	-*v* ) exit ;;
	-[ai] ) shift ;;
	-e ) shift; break ;;
	-* ) shift 2 ;;
esac done

tmux split-window -t:.0 $@ \; \
	swap-pane -s:.0 -t:.1
