#!/bin/sh

# sb-battery wrapper for Termux

status="$(termux-battery-status)"
status="${status#*status\": \"}"
status="${status%%\"*}"

case "$status" in
	FULL ) status="⚡" ;;
	DISCHARGING ) status="🔋" ;;
	CHARGING ) status="🔌" ;;
	"NOT CHARGING" ) status="🛑" ;;
	UNKNOWN ) status="♻️" ;;
	* ) exit 1 ;;
esac

capacity="$(termux-battery-status)"
capacity="${capacity#*percentage\": }"
capacity="${capacity%%,*}"

[ "$status" = "🔋" ] && [ "$capacity" -le 25 ] && warn="❗"

printf "%s%s%d%%\n" "$status" "$warn" "$capacity"
