#!/bin/sh

# setbg wrapper for Termux

# This script does the following:
#	If given a file, set that as the new wallpaper.
#	If given a directory, choose random file in it.
#	If wal is installed, also generates a colorscheme.

# Location of link to wallpaper link.
bgloc="${XDG_DATA_HOME:-$HOME/.local/share}/bg"

# Configuration files of applications that have their themes changed by pywal.
dunstconf="${XDG_CONFIG_HOME:-$HOME/.config}/dunst/dunstrc"
zathuraconf="${XDG_CONFIG_HOME:-$HOME/.config}/zathura/zathurarc"
termuxconf="${XDG_CONFIG_HOME:-$HOME/.config}/termux/colors.properties"
tmuxconf="${XDG_CONFIG_HOME:-$HOME/.config}/tmux/tmux.conf"

# Give -s as parameter to make notifications silent.
while getopts "s" o; do case "$o" in
	s) silent=1 ;;
esac done

shift $((OPTIND - 1))

trueloc="$(readlink -f "$1")" \
	&& case "$(file --mime-type -b "$trueloc")" in
		image/* )
			ln -sf "$trueloc" "$bgloc" \
				&& [ -z "$silent" ] \
				&& notify-send \
				-i "$bgloc" \
				"Changing wallpaper..."
			;;
		inode/directory )
			ln -sf "$(find "$trueloc" -iregex \
				".*.\(jpg\|jpeg\|png\|gif\)" \
				-type f | shuf -n 1)" "$bgloc" \
				&& [ -z "$silent" ] \
				&& notify-send \
				-i "$bgloc" \
				"Random Wallpaper chosen."
			;;
		* )
			[ -z "$silent" ] \
				&& notify-send \
				"🖼️ Error"\
				"Not a valid image or directory."
			exit 1
			;;
esac

# If pywal is installed, use it.
if command -v wal >/dev/null 2>&1; then
	wal -n \
		-i "$(readlink -f "$bgloc")" \
		-o "${XDG_CONFIG_HOME:-$HOME/.config}/wal/postrun" \
		>/dev/null 2>&1
	xargs sh -c 'printf "color0=%s\\ncolor1=%s\\ncolor2=%s\\ncolor3=%s\\ncolor4=%s\\ncolor5=%s\\ncolor6=%s\\ncolor7=%s\\ncolor8=%s\\ncolor9=%s\\ncolor10=%s\\ncolor11=%s\\ncolor12=%s\\ncolor13=%s\\ncolor14=%s\\ncolor15=%s\\n\\ncursor=%s\\nbackground=%s\\nforeground=%s\\n" "${0}" "${1}" "${2}" "${3}" "${4}" "${5}" "${6}" "${7}" "${8}" "${9}" "${10}" "${11}" "${12}" "${13}" "${14}" "${15}" "${6}" "${0}" "${6}"' \
		<"${XDG_CACHE_HOME:-$HOME/.cache}/wal/colors" \
		>"${XDG_CACHE_HOME:-$HOME/.cache}/wal/termux.properties"
	mv -n "$termuxconf" "$termuxconf.bak"
	ln -sf "${XDG_CACHE_HOME:-$HOME/.cache}/wal/termux.properties" \
		"$termuxconf"
else
# If pywal is removed, return config files to normal.
	[ -f "$dunstconf.bak" ] \
		&& unlink "$dunstconf" \
		&& mv "$dunstconf.bak" "$dunstconf"
	[ -f "$zathuraconf.bak" ] \
		&& unlink "$zathuraconf" \
		&& mv "$zathuraconf.bak" "$zathuraconf"
	[ -f "$termuxconf.bak" ] \
		&& unlink "$termuxconf" \
		&& mv "$termuxconf.bak" "$termuxconf"
fi

termux-wallpaper -f "$bgloc" >/dev/null 2>&1
termux-wallpaper -l -f "$bgloc" >/dev/null 2>&1

termux-reload-settings
tmux source-file "$tmuxconf" >/dev/null 2>&1
