# Appearance
disable-terminal-session-change-toast = true
fullscreen = false

# Vlinking timeout for the terminal blinking attribute
# Default: 800
# Disable: 0
terminal-cursor-blink-rate = 0

# Bell volume. vibrate, beep, or ignore
bell-character = ignore

# Default shape of cursor
# block ("█")
# underline ("_")
# bar ("|")
terminal-cursor-style = bar

# Uncomment this if having keyboard problems
# enforce-char-based-input = true

# Volume buttons
volume-keys = volume

# Extra keys
extra-keys-text-all-caps = false
extra-keys = [ \
  [ \
    { key: ESC, display: 'Esc', popup: \
      { macro: 'ESC : q ENTER', display: ':q' } }, \
    { macro: 'CTRL b', display: '🐧', popup: \
      { key: KEYBOARD, display: '≣' } }, \
    { macro: 'ESC $', display: '$', popup: \
      { key: '$', display: '$' } }, \
    { key: UP, display: '↑' }, \
    { macro: 'ESC 0', display: '0', popup: \
      { key: '0', display: '0' } }, \
    { key: ':', display: ':', popup: \
      { key: '`', display: '`' } } \
  ], \
  [ \
    { key: '	', display: 'Tab ↹', popup: \
      { macro: 'ESC : w q ENTER', display: ':wq' } }, \
    { key: CTRL, display: 'Ctrl', popup: \
      { macro: 'ESC : w ENTER', display: ':w' } }, \
    { key: LEFT, display: '←' }, \
    { key: DOWN, display: '↓' }, \
    { key: RIGHT, display: '→' }, \
    { key: '/', display: '/', popup: \
      { key: '\\\\', display: '\\\\' } } \
  ] \
]
